default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"

se-connecter:
  controller: "Security"
  action: "login"

deconnexion:
  controller: "Security"
  action: "logout"

